{
 "title": "Mobile price service dashboard",
 "time": { "from": "2025-11-14T02:02:45.609Z", "to": "2025-11-16T02:02:45.609Z" },
 "panels": [
  {
   "title": "use level metricks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{method=\"POST\", status=~\"2xx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{method=\"POST\", status=~\"4xx\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_requests_total{method=\"POST\", status=~\"5xx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infrastructure Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Destribution from DB",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "mobile_price_prediction_db",
     "rawSql": "SELECT result FROM mobile_predictions LIMIT 50 "
    }
   ]
  }
 ]
}